/// Flutter icons Toutiao
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Toutiao
///      fonts:
///       - asset: fonts/Toutiao.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Toutiao {
  Toutiao._();

  static const _kFontFam = 'Toutiao';

  static const IconData zhaoxiang = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData sousuo = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bofang = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData V = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData mmyy = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData liuyan = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData shoujishipin = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData bofang1 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData shipin = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData up = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData gengduo = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData shoucang = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData more1 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData lishi = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData bofang2 = const IconData(0xe810, fontFamily: _kFontFam);
}
